### ISSUE TITLE
Is there any release plan for version 1.2.0?

### ISSUE THREAD

**Issue by thuchenyusi** [vishvananda/netlink#1005]
We only have a beta version for 1.2.x at the moment. Is there a release plan for the stable version of 1.2.0?

**Comment by tklauser** [comment]
Also see https://github.com/vishvananda/netlink/issues/612

cc @vishvananda @aboch

**Comment by aboch** [comment]
https://github.com/vishvananda/netlink/releases/tag/v1.2.1
