### ISSUE TITLE
ip netns

### ISSUE THREAD

**Issue by c4milo** [vishvananda/netlink#12]
Where do you think code to implement `ip netns` commands should live? this project, https://github.com/vishvananda/netns perhaps? somewhere else?

**Comment by vishvananda** [comment]
closing this because I haven't heard a response in a month. Feel free to re-open for further discussion

**Comment by c4milo** [comment]
I was using it to configure guests networking from the hosts, only that.
Sorry for the late response.

On Wednesday, January 14, 2015, Vish Ishaya <notifications@github.com>
wrote:

> closing this because I haven't heard a response in a month. Feel free to
> re-open for further discussion
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vishvananda/netlink/issues/12#issuecomment-69873661>.
>


-- 
Sent from Gmail Mobile

**Comment by vishvananda** [comment]
Ok so I think you should be able to do that using the netns library in combination with this lib.

**Comment by c4milo** [comment]
indeed, thank you!
