### ISSUE TITLE
rtm_type is missing on purpose?

### ISSUE THREAD

**Issue by catinello** [vishvananda/netlink#130]
I can't find the rtm_type's or any other way to define those in routes/rules. Are they missing on purpose? Or is this a work in progress?

>               rtm_type          Route type
              ───────────────────────────────────────────────────────────
              RTN_UNSPEC        unknown route
              RTN_UNICAST       a gateway or direct route
              RTN_LOCAL         a local interface route
              RTN_BROADCAST     a local broadcast route (sent as a
                                broadcast)
              RTN_ANYCAST       a local broadcast route (sent as a
                                unicast)
              RTN_MULTICAST     a multicast route
              RTN_BLACKHOLE     a packet dropping route
              RTN_UNREACHABLE   an unreachable destination
              RTN_PROHIBIT      a packet rejection route
              RTN_THROW         continue routing lookup in another table
              RTN_NAT           a network address translation rule
              RTN_XRESOLVE      refer to an external resolver (not
                                implemented)

http://man7.org/linux/man-pages/man7/rtnetlink.7.html

I tried the following to get a default route on table 127 which points to a blackhole: (ip route add blackhole default table 127)

>         src := net.IPv4(0, 0, 0, 0)
         route := nl.Route{LinkIndex: link.Attrs().Index, Src: src, Type: syscall.RTN_BLACKHOLE, Table: 127}
         if err := nl.RouteAdd(&route); err != nil {
                panic(err)
         }

Table 127 is empty and no matter what I still receive a panic.

> panic: invalid argument

 

Thank you for this netlink library.

**Comment by catinello** [comment]
Nevermind, got it! Looked at the iproute2 code for a hint. No link needed.

**Comment by xaviershay** [comment]
I was looking for these. They're defined in https://godoc.org/golang.org/x/sys/unix
