### ISSUE TITLE
Subscribe functions should be exposed as methods of handles

### ISSUE THREAD

**Issue by clinta** [vishvananda/netlink#141]
I have a need to subscribe to routes and links in a different namespace, exposing the subscribe functions as methods of a netlink handle would be very helpful.

**Comment by aboch** [comment]
As of now it cannot be a method of Handle because once created Handle has no information about the netns it was created for. 
In my opinion we could add a
`SubscribeAt(newNs, curNs netns.NsHandle,protocol int, groups ...uint)` method, in line with `GetNetlinkSocketAt()`

**Comment by clinta** [comment]
That would work too.
