### ISSUE TITLE
replace default gateway

### ISSUE THREAD

**Issue by vtolstov** [vishvananda/netlink#15]
How can i replace default gateway with this package?

**Comment by vishvananda** [comment]
You would need to delete the route with Dst set to nil (this is the default route), then add a new route with Dst == nil

**Comment by vtolstov** [comment]
thanks, i'm try. But i think that high level api needs to be present, iproute2 have ip route replace....

**Comment by fmzhen** [comment]
In the function `routeHandle(route *Route, req *nl.NetlinkRequest, msg *nl.RtMsg) error` , have the following code

```
	if (route.Dst == nil || route.Dst.IP == nil) && route.Src == nil && route.Gw == nil {
		return fmt.Errorf("one of Dst.IP, Src, or Gw must not be nil")
	}
```

So, if the Dst = nil, i clould not delete the default route. How i delete the default route with netlink.  Jult like " ip route del default "
ping @vishvananda

**Comment by vishvananda** [comment]
You can specify the gateway on delete.

**Comment by fmzhen** [comment]
If  i don't know the `route.Src` and `route.Gw`. How can i delete .    I just know the Dst is 0.0.0.0
 @vishvananda

**Comment by vishvananda** [comment]
Use RouteList to find the gateway. That said it may work to just pass an
empty gateway for delete. I would have to test.
Vish

**Comment by fmzhen** [comment]
I used the following code to successfully delete the default route in docker container

```
	routes, _ := netlink.RouteList(nil, netlink.FAMILY_V4)
	for _, r := range routes {
		if r.Dst == nil {
			fmt.Println(r)
			if err := netlink.RouteDel(&r); err != nil {
				fmt.Println(err)
			}
		}
	}
```
But in my host, i get error "no such process "  .  I have the default route in my host ,gw is 10.10.105.254.  The output is following
```
{Ifindex: 2 Dst: <nil> Src: <nil> Gw: 10.10.105.254}
no such process
```
@vishvananda
