### ISSUE TITLE
rule priority defaults to table id value when used with table id higher than 255

### ISSUE THREAD

**Issue by pyakpyak** [vishvananda/netlink#150]
I'm trying to set a rule which look like this:
`sudo ip rule add to 200.200.200.200 lookup 500 priority 3000`

produces the following ip rule output:
`3000:  from all to 200.200.200.200 lookup 500`

If the same operation applied with `netlink`:

> _, dstIpNet, _ := net.ParseCIDR("200.200.200.200/32")
> _, srcIpNet, _ := net.ParseCIDR("0.0.0.0/0")
> 
> rule := netlink.NewRule()
> rule.Src = dstIpNet
> rule.Dst = srcIpNet
> rule.Priority = 3000
> rule.Table = 500
> netlink.RuleAdd(rule)`

It produces the following `ip rule` output:
`500:   from 200.200.200.200 lookup 500`

I'm not sure what is the official support status for table ids higher than 255 in the recent kernels? It works fine with CLI and It looks like IDs > 255 work fine in `netlink` if we don't specify the `priority` field. 

I tested it on `3.13.0-76-generic #120-Ubuntu`

Any ideas?

**Comment by vishvananda** [comment]
This looks suspiciously like a bug where nl expects the priority to be
passed differently for tables higher than 255. If you use a lower table
number, does it work?

**Comment by pyakpyak** [comment]
Yes, priority + lower table numer (<255) works properly
