### ISSUE TITLE
Does this lib support NETLINK_INET_DIAG family?

### ISSUE THREAD

**Issue by liuyangc3** [vishvananda/netlink#153]

**Comment by raboof** [comment]
AFAICS it does not, but I'd like it to :)

**Comment by gwind** [comment]
NO, but [nl/nl_linux.og](https://github.com/vishvananda/netlink/blob/master/nl/nl_linux.go) has a common netlink request design.

I've write a test, like `ss -t`.

https://gist.github.com/gwind/05f5f649d93e6015cf47ffa2b2fd9713

**Comment by raboof** [comment]
Cool! I ended up using https://github.com/eleme/netlink (https://github.com/raboof/connbeat/blob/master/sockets/tcp_diag/tcp_diag.go), but this looks good too.

**Comment by t57root** [comment]
@gwind , I'm wondering why you didn't commit your inetdiag code to this project? 
Is this project not willing to accept this feature?

**Comment by aboch** [comment]
Closing as this is not really an issue, and the question was answered.

>@gwind , I'm wondering why you didn't commit your inetdiag code to this project?
Is this project not willing to accept this feature?

Contributions to this projects are always welcomed.
