### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by vtolstov** [vishvananda/netlink#16]
```
netlink.RouteAdd(&netlink.Route{LinkIndex: 2, Dst: nil})
```

How can i add default route ?

**Comment by vtolstov** [comment]
Alsa when i try to get RouteList, i getting  empty slice for route, and error is nil. 
I think this is not right....

**Comment by vishvananda** [comment]
What is the version of go and your kernel?

**Comment by vishvananda** [comment]
You need to be root to add routes fyi

**Comment by vtolstov** [comment]
I'm try to get routes list, but it empty.I run under root

**Comment by vtolstov** [comment]
https://github.com/docker/libcontainer/pull/169 for libcontainer I need fix for gateway routes.. May be something needs to..
I have 3.14 kernel,but my program runs by kernel (i m write init replacement)

**Comment by vtolstov** [comment]
Also I think that we need to check that in route DST is not nil. Not only IP in DST 

func routeHandle(route *Route, req *nl.NetlinkRequest) error {
	if route.Dst.IP == nil && route.Src == nil && route.Gw == nil {
		return fmt.Errorf("one of Dst.IP, Src, or Gw must not be nil")
	}

**Comment by vishvananda** [comment]
ah that is a good point, will make that change.

**Comment by vtolstov** [comment]
Now all works fine. I'm fix my errros.
