### ISSUE TITLE
Use uint32 on MTU

### ISSUE THREAD

**Issue by HuKeping** [vishvananda/netlink#163]
Hi there,

As per https://en.wikipedia.org/wiki/Maximum_transmission_unit

Even when we under IPv6, the maximum MTU will not over 4294967296 (2^32-1), so I wonder if it make sense to use `uint32` instead of `int` on MTU?

**Comment by vishvananda** [comment]
Generally I've been trying to use ints on the high level interface so you
don't have to worry about the appropriate type for the low level Berlin
calls.

Vish

**Comment by vishvananda** [comment]
s/Berlin/netlink/

**Comment by HuKeping** [comment]
Thanks for checking this @vishvananda !
