### ISSUE TITLE
Running the tests crashes my system

### ISSUE THREAD

**Issue by raboof** [vishvananda/netlink#166]
uname -a is `Linux yinka 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux`

**Comment by aboch** [comment]
Please provide more info. kernel version and what test caused the crash. Please also try latest version, where some tests are executed only if the feature is supported by the kernel.

**Comment by raboof** [comment]
Tried latest master (now on `Linux yinka 4.14.0-rc3-amd64 #1 SMP Debian 4.14~rc3-1~exp1 (2017-10-02) x86_64 GNU/Linux`) and though some tests failed my system did not crash.
