### ISSUE TITLE
Bond modes numbers are not consistent with linux

### ISSUE THREAD

**Issue by RostyslavFridman** [vishvananda/netlink#177]
According to this https://godoc.org/github.com/vishvananda/netlink#BondMode documentation, constants are not correct. It should be as following:
https://www.kernel.org/doc/Documentation/networking/bonding.txt

**Comment by vishvananda** [comment]
Thanks for reporting this. It does look like they are out of order. I'll fix them unless @marek-polewski has any comments regarding the ordering.

**Comment by marek-polewski** [comment]
Hi,
Yeach, this looks like error on my side. I was implementing that basing on iproute source code and there order is also the same as in kernel docs. So you are right guys.
