### ISSUE TITLE
Tests fail to build on linux/s390x

### ISSUE THREAD

**Issue by mundaym** [vishvananda/netlink#194]
In https://github.com/golang/go/issues/18628 it was reported that the tests for this package fail to build on linux/s390x because the `syscall.IfInfomsg.X__ifi_pad` field isn't exported.

I've sent a CL to (maybe) get the field exported for Go 1.8 but would it be possible to remove the dependence on the value of the `X__ifi_pad` field from the tests in nl/nl_linux_test.go? Failing that, maybe it would be reasonable to skip building this file on s390x for now (i.e. add `// +build !s390x` to the top of the file)?

Also, out of interest do you know if the value of the `X__ifi_pad` field matters in any way (if it does it would help me make the case for getting it exported in the syscall library)?

Thanks.

cc @sharkcz

**Comment by vishvananda** [comment]
I changed the test to not try to write the pad value. That should fix your issue.

**Comment by mundaym** [comment]
Yup, that fixes the issue, thanks!
