### ISSUE TITLE
Compatibility with Go 1.6

### ISSUE THREAD

**Issue by iwaseyusuke** [vishvananda/netlink#215]
Hi Team!

I faced the compatibility problem with Go 1.6 (via apt package on Ubuntu 16.04 LTS).
```
$ go get -t ./...
# github.com/vishvananda/netlink
../../vishvananda/netlink/conntrack_linux.go:170: undefined: io.SeekCurrent
../../vishvananda/netlink/conntrack_linux.go:176: undefined: io.SeekCurrent
../../vishvananda/netlink/conntrack_linux.go:186: undefined: io.SeekCurrent
../../vishvananda/netlink/conntrack_linux.go:221: undefined: io.SeekCurrent
../../vishvananda/netlink/conntrack_linux.go:243: undefined: io.SeekCurrent
```
Does anyone know why?

Thanks

**Comment by fcrisciani** [comment]
Looks like in go 1.6 io.SeekCurrent was not defined yet, I pushed a PR to address it

**Comment by iwaseyusuke** [comment]
Thanks @fcrisciani !

BTW, how about adding Travis-CI tests with the multiple version (1.6, 1.7 and 1.8)?
Please see [this Travis-CI Doc](https://docs.travis-ci.com/user/languages/go/#Specifying-a-Go-version-to-use).

**Comment by fcrisciani** [comment]
@iwaseyusuke no problem
