### ISSUE TITLE
HtbClass rate and ceil use bits or bytes？

### ISSUE THREAD

**Issue by langyxxl** [vishvananda/netlink#235]
I found in file "class_linux.go" "func NewHtbClass" use bytes
rate := cattrs.Rate / 8
ceil := cattrs.Ceil / 8

but in "func parseHtbClassData" use bits
htb.Rate = uint64(opt.Rate.Rate)
htb.Ceil = uint64(opt.Ceil.Rate)

Is this a bug?

**Comment by chantra** [comment]
I most likely coded that a while back. IIRC I was mimicking what is done by iproute: https://github.com/shemminger/iproute2/blob/707f612c00a91fe3c17d7af5319e423545a496c5/tc/tc_util.c#L156

Basically, the interface is in bits, but tc expect bytes. I suppose I never had to deal much with the reading from netlink. I agree there may be some discrepancy between the expectation of setting vs getting parameters.

**Comment by vishvananda** [comment]
Yes it does look like it should be converted to bits on the way out as well. Also I can't remember why there is a second copy of most of the fields in the htbclass. @chantra do you remember?

**Comment by chantra** [comment]
@vishvananda I suppose this is because a HtbClass contains both ClassAttrs and HtbClassAttrs and HtbClass glues things together... it has been a while sinmce I touched that so I cant remember. One totally possible reason is that my golang-fu is pretty weak and this is just a solution I came up with when I should probably have coded it another way.

**Comment by aboch** [comment]
`tc` command allows the user to specify the unit for the rate value via well-known suffixes.
The referenced iproute2 implementation assumes the unit for the user-inputed value to be `bit per second` _only_ when no unit suffix is passed. 

Regardless, it then applies the respective "to bits per second" scaling factor and divides by 8 and stores in `rate` or `ceil`. Like to say, the unit for `rate` and `ceil` is _bytes per second_.

In fact, looking at the kernel code, that seems to be the case.

So `parseHtbClassData` does the right thing, it stores the kernel returned `rate` and `ceil` values as is. 

The user facing API data, `HtbClassAttrs`, not having an option for specifying the units, it is IMO correctly expecting the inputted values to be in _bits per second_, as this is  the only way to give the user the ability to specify the values with the highest granularity. Also, using uint64, there is no concern about being able to specify TBps rates in bits/sec.

And `NewHtbClass` does the expected thing, it converts the user passed values from bits/sec to bytes/sec.

Closing then, as this is not an issue.

**Comment by aboch** [comment]
We should probably add comments to `HtbClassAttrs` to make it clear `Rate` and `Ceil` inputted attributes are expected in _bits per second_
