### ISSUE TITLE
Build fails on Mac because of undefined variables

### ISSUE THREAD

**Issue by kklin** [vishvananda/netlink#243]
```
$ go build .
# github.com/vishvananda/netlink
./filter.go:189: undefined: nl.TC_U32_TERMINAL
./filter.go:190: undefined: nl.TC_U32_OFFSET
./filter.go:191: undefined: nl.TC_U32_VAROFFSET
./filter.go:192: undefined: nl.TC_U32_EAT
```

It looks like the errors are because the constants are defined in a `_linux` file: https://github.com/vishvananda/netlink/blob/master/nl/tc_linux.go#L471.

**Comment by serngawy** [comment]
I have the same issue, does anyone had a fix for it

**Comment by supernomad** [comment]
I have the same issue, but when attempting to compile on FreeBSD.

**Comment by trevrosen** [comment]
I moved the offending lines from `filter.go` into `filter_linux.go` and all was well. I'm going to PR.
