### ISSUE TITLE
Does netlink support  "ip rule add not to 10.0.0.0/16 table main"

### ISSUE THREAD

**Issue by liwenwu-amazon** [vishvananda/netlink#276]
I have trouble figuring out how to use netlink package to perform linux command "ip rule add not to 10.0.0.0/16 table main"

I have seen following code in C 
...
 if (strcmp(*argv, "not") == 0) {
            req.r.rtm_flags |= FIB_RULE_INVERT;
...
but can NOT find similar definition in GO

**Comment by vishvananda** [comment]
it doesn't currently support inversion, but a patch to add it shouldn't be to difficult
