### ISSUE TITLE
Question: Library scope

### ISSUE THREAD

**Issue by nseps** [vishvananda/netlink#278]
If i understand correctly, this library supports only specific netlink families (NETLINK_ROUTE, NETLINK_XFRM, NETLINK_NETFILTER)

Are there any plans to make this a more generic netlink library by supporting families like NETLINK_ISCSI or NETLINK_KOBJECT_UEVENT for example?

**Comment by vishvananda** [comment]
There are no plans to expand the library beyond network related functions, but contributions are welcome.

**Comment by nseps** [comment]
Understood. Thanks for replying!
