### ISSUE TITLE
Call for Maintainers

### ISSUE THREAD

**Issue by vishvananda** [vishvananda/netlink#279]
Hello Everyone,

I'm working on a proposal to contribute the netlink library to https://github.com/containernetworking. As part of the discussion with the cni maintainers, we identified the need to bring on some more maintainers for netlink.

I've been maintaining netlink on my own for 3 years. It is currently in use by a ton of projects, including all of the network-related container plugins and utilitites. If anyone would like to help maintain the library, please let me know.

**Comment by fcrisciani** [comment]
@vishvananda count on me if you want

**Comment by vishvananda** [comment]
@aboch would you be interested in becoming a maintainer?

**Comment by aboch** [comment]
Hi @vishvananda, thank you for your proposal.
Yes, I am interested.

**Comment by vishvananda** [comment]
@fcrisciani could you send a message to the email on my profile so we could discuss?  Thanks.

**Comment by supernomad** [comment]
I am a relatively new user of your library but would be more than happy to assist if you are still in need.

**Comment by fbegyn** [comment]
In case your still looking, I'd be willing to pitch in. Currently doing work on implementing HFSC into this library.

**Comment by vishvananda** [comment]
@supernomad @fbegyn thank you for the offer. I think we are ok with maintainers thanks to the work from @aboch and @fcrisciani . I will let you know if we need more in the future. If you would like to help review prs or fix issues, however, we could always use the help.
