### ISSUE TITLE
What's the equivalent API of `ip route show table local type local`

### ISSUE THREAD

**Issue by m1093782566** [vishvananda/netlink#302]
Hi all,

Is there any equivalent API of `ip route show table local type local` in netlink?

**Comment by aboch** [comment]
Have you tried 'RouteListFiltered' ?
In the 'Route' parameter you would specify the 'Type' as local.

**Comment by m1093782566** [comment]
Thanks @aboch 

BTW, should we only specify one of  `FAMILY_V4` and `FAMILY_V6` in the `family` parameter of 

`RouteListFiltered(family int, filter *Route, filterMask uint64)` ?

How can we list both IPV4 and IPV6 addresses?

**Comment by aboch** [comment]
https://github.com/vishvananda/netlink/blob/6e7bb56ca47cfb10667c44949ff6fe2af3d91c66/netlink_linux.go#L7
