### ISSUE TITLE
What's the difference between LinkIndex and ILinkIndex in netlink.Route?

### ISSUE THREAD

**Issue by m1093782566** [vishvananda/netlink#306]
**Question:**

What's the difference between `LinkIndex` and `ILinkIndex` in `netlink.Route`? I can't find any comment message in the code base.

I want to find the equivalent netlink API of command

```
ip route show table local type local proto kernel dev eth0
```

I guess we can pass the link index of `eth0`, e.g

```
linkIndex := LinkByName("eth0")
```

in `netlink.Route` as a filter for `RouteListFiltered()`,

However, I feel confused that whether we should assign the value `linkIndex` to `Route.LinkIndex` or `Route.ILinkIndex`?

@vishvananda @aboch any comments?

**Comment by jjastrze-ovh** [comment]
In most cases you should you use Route.LinkIndex
ILinkIndex is for some incoming link index.

**Comment by m1093782566** [comment]
@jjastrze-ovh thanks!
