### ISSUE TITLE
freebsd support

### ISSUE THREAD

**Issue by vtolstov** [vishvananda/netlink#31]
Please add minimal freebsd support to netlink package.

**Comment by dave-tucker** [comment]
As far as I know, freebsd doesn't have support for netlink...

**Comment by emaste** [comment]
FreeBSD does support netlink, see e.g. https://man.freebsd.org/cgi/man.cgi?query=netlink&manpath=freebsd-release-ports

> The netlink protocol appeared in FreeBSD 13.2.
