### ISSUE TITLE
IPv6 address not handled properly for Gretun

### ISSUE THREAD

**Issue by KireinaHoro** [vishvananda/netlink#316]
In iproute2, IPv6 GRE tunnels are called "ip6gre"'s. The current implementation will result in mysterious "file exists" errors when trying to add a Gretun object.

**Comment by aboch** [comment]
Thank you for reporting this. Please post a sample go code which shows the issue, and we will go from there, unless you are already working to a patch for it.

**Comment by KireinaHoro** [comment]
@aboch 

```go
package main

import (
    "github.com/vishvananda/netlink"
    "log"
    "net"
    "fmt"
)

func main() {
    la := netlink.NewLinkAttrs()
    la.Name = "foobar"

    l, err := netlink.LinkByName(la.Name)
    if err == nil {
        log.Fatalf("Link with name %s already exists: %v", la.Name, err) // HERE
    } else {
        myGretun := &netlink.Gretun{LinkAttrs: la}
        myGretun.Remote = net.ParseIP("2001:da8::1")
        myGretun.Local = net.ParseIP("2001:da8::2")
        err := netlink.LinkAdd(myGretun)
        if err != nil {
            log.Fatalf("Could not add %s: %v", la.Name, err)
        }
        l = myGretun
    }
    fmt.Printf("Information about the created link: %v", l)
}
```

If the `file exists` comes from an existing interface `foobar`, we'll get the error message from the line where `HERE` marked. Yet it's not behaving that way. The message I get is:

> 2018/01/19 02:39:06 Could not add foobar: file exists

**Comment by aboch** [comment]
Thank you.

Yes, the GRE link add part assumes local/remote addresses must be IPv4.
So when you pass v6 addresses, netlink msg to kernel will have nil local/remote IP.
The returned erroris misleading.
