### ISSUE TITLE
You have added GPLed code to your library, your license is now incorrect

### ISSUE THREAD

**Issue by Omnifarious** [vishvananda/netlink#323]
This line of this commit: https://github.com/vishvananda/netlink/commit/43948793f6d3a2c029b5bd3399d70904b910d668#diff-3a75c4e0509f2a1ae3e9fd2fcc8c6a2fR73

makes your whole library now a GPL library. I hope you realize this. The license file is now incorrect.

**Comment by aboch** [comment]
@brb Please fix that comment, referring to the logic explained in the appendix of https://www.ietf.org/rfc/rfc4303.txt on how you derive the bitmap length.

**Comment by brb** [comment]
@Omnifarious Thanks for pointing.

The linked comment supposed to mean "logic is taken from ...", and the code is not a copy-paste from https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/ip/xfrm_state.c#n590 

I'm wondering whether the case still applies?

**Comment by aboch** [comment]
@Omnifarious I agree with @brb`s point.
In order to avoid future confusion, I opened #324 to make the logic clear.

**Comment by Omnifarious** [comment]
@aboch , @brb - Thank you. That addresses my concern nicely.
