### ISSUE TITLE
h.LinkByName(name): How to resolve err when name is nil

### ISSUE THREAD

**Issue by stewart-yu** [vishvananda/netlink#325]
when name is nil, the return err is "Link not found" seems the type is  string, have an standred status code to recognize it?

**Comment by aboch** [comment]
AFAIK, this library APIs will always return an error of type `error`.

In your case, it could be of type `LinkNotFoundError`.

https://github.com/vishvananda/netlink/blob/master/link.go#L844

```
// LinkNotFoundError wraps the various not found errors when
// getting/reading links. This is intended for better error
// handling by dependent code so that "not found error" can
// be distinguished from other errors
type LinkNotFoundError struct {
	error
}
```

**Comment by m1093782566** [comment]
@aboch 

Do you mean we can cast the error to *LinkNotFoundError?

**Comment by aboch** [comment]
@m1093782566 

Something like this ?

```
if _, ok := err.(netlink.LinkNotFoundError); ok {
...
}
```

**Comment by christarazi** [comment]
@aboch That API is not quite friendly for Go 1.13 semantics where `errors.Is` is recommended. However, I realize that changing `LinkNotFoundError` would be a breaking change. Just thought I'd mention this since I couldn't find anyone who noted this down in this repo.

**Comment by aboch** [comment]
> @aboch That API is not quite friendly for Go >=1.13 semantics where `errors.Is` is recommended. However, I realize that changing `LinkNotFoundError` would be a breaking change. Just thought I'd mention this since I couldn't find anyone who noted this down in this repo.

Thanks @christarazi 
Feel free to propose and work to an alternative.
