### ISSUE TITLE
Adding a blackhole route

### ISSUE THREAD

**Issue by karampok** [vishvananda/netlink#326]
Hi!
I have been trying to add a blackhole route using the library, but without success.
What  I mean is the following `ip route` command
` ip route add blackhole 192.168.0.195/32`

Does the library supports it? 

Thx!

**Comment by aboch** [comment]
Ideally you would achieve that by setting `Type = unix. RTN_BLACKHOLE` in the `Route` structure.
If that does not work, then there must be a bug somewhere.

**Comment by karampok** [comment]
Seems to work, thx!
