### ISSUE TITLE
How to create route object?

### ISSUE THREAD

**Issue by pmichali** [vishvananda/netlink#328]
Maybe this is just a documentation issue, but I want to do the equivalent of:

```
ip route add 172.18.0.128/25 via 172.18.0.200
ip route del 172.18.0.128/25 via 172.18.0.200
```

I see a RouteAdd() and RouteDel(), and info on the Route struct, but for the life of me, do not know how to properly form the Route struct.

Additionally, I don't know the device name, as it is on a bridge interface that is created indirectly via a "docker run" command.

I was thinking I could do a RouteGet() on the subnet that was created for the docker container to get a Route, and then try to modify that to change the dst (172.18.0.128/25), gw (172.18.0.200), src(0.0.0.0?), and flags (how to set the G flag?), but this seems really complicated (besides I'm not sure about two items.

Any advice?

**Comment by phob0s-pl** [comment]
If you don't know the interface name, you can search it:

```go
	route := &netlink.Route{
		Dst: &net.IPNet{IP: net.ParseIP("192.168.18.0"), Mask: net.CIDRMask(24, 32)},
		Src: net.ParseIP("192.168.88.227"),
	}
	list, _ := netlink.LinkList()
	for i := range list {
		addrs, _ := netlink.AddrList(list[i], nl.FAMILY_V4)
		for j := range addrs {
			if addrs[j].IP.Equal(route.Src) {
				fmt.Println("Using interface", list[i].Attrs().Name)
				route.LinkIndex = list[i].Attrs().Index
			}
		}
	}
	netlink.RouteAdd(route)
```

**Comment by phob0s-pl** [comment]
If you don't know interface you can try:

```go
	route := &netlink.Route{
		Dst: &net.IPNet{IP: net.ParseIP("192.168.18.0"), Mask: net.CIDRMask(24, 32)},
		Gw:  net.ParseIP("192.168.88.1"),
	}
	list, _ := netlink.LinkList()
	for i := range list {
		neighs, _ := netlink.NeighList(list[i].Attrs().Index, nl.FAMILY_V4)
		for j := range neighs {
			if neighs[j].IP.Equal(route.Gw) {
				fmt.Println("Using interface", list[i].Attrs().Name)
				route.LinkIndex = list[i].Attrs().Index
			}
		}
	}
	netlink.RouteAdd(route)
```

**Comment by pmichali** [comment]
Thanks! I was able to get a variant of that working, by using the netlink.AddrList() and checking to see if one of the addresses was in the subnet of the enclosing network (the bridge has a network of 172.18.0.0/16)

**Comment by pmichali** [comment]
Thanks! From one of your suggestions, I was able to use the CIDR of the subnet used for the bridge to obtain the index of the interface:

```
	_, c, err := net.ParseCIDR(cidr)
	if err != nil {
		return 0, fmt.Errorf("Unable to parse CIDR %q: %s", cidr, err.Error())
	}
	links, _ := netlink.LinkList()
	for _, link := range links {
		addrs, _ := netlink.AddrList(link, nl.FAMILY_V4)
		for _, addr := range addrs {
			if c.Contains(addr.IP) {
				glog.V(4).Infof("Using interface %s (%d) for CIDR %q", link.Attrs().Name, link.Attrs().Index, cidr)
				return link.Attrs().Index, nil
			}
		}
	}
	return 0, fmt.Errorf("Unable to find interface for CIDR %q", cidr)
```

Used that to build the Route object. In cases where I knew the interface name, I used LinkByName().
