### ISSUE TITLE
64K buffer allocation on every call causes lots of garbage-collection

### ISSUE THREAD

**Issue by bboreham** [vishvananda/netlink#379]
#365 increased the buffer size from (typically) 4K to 64K.
The cost of garbage-collection in Go is broadly driven by how many bytes/sec you allocate, so this change is rather painful if you do a lot of netlink calls.

Currently `Receive()` allocates the buffer and returns it to `Execute()`, which may return slices pointing into the buffer.  So we cannot have `Receive()` re-use buffers or use a buffer on the stack without changing this behaviour.

In about 70% of cases the return from `Execute()` is discarded.

If another entrypoint were added to allow the buffer to be passed in, the buffer could come from the stack of the caller and all this allocation and garbage-collection could be avoided.  But at the cost of some extra ugliness at every call site.

Since #365 notes that only some calls need a larger buffer, perhaps we could change only those calls that need a larger buffer and put the standard buffer back to `Getpagesize()` ?

**Comment by jellonek** [comment]
The correct solution should be to handle truncate flag (msg.msg_flags & MSG_TRUNC) and read next pack of data if kernel sets this flag. So probably we need to tune a bit [this](https://github.com/jellonek/netlink/blob/a74caa6f29c2ad31f7909e00b760f6bc888177dc/nl/nl_linux.go#L418) loop.
If this issue with 64k causes so big performance lose we can add temporarily a pair of func `LargeExecute`/`LargeReceive` and use it in problematic parts of code in place of `Execute`, but for sure one of such places will be `LinkList` which is quite crucial (and used by all `LinkBySomething` funcs) and probably one of most used from whole library, so it still will require guarding by larger buffer, so whole effort at the end will fix only a small part of whole bigger issue.

**Comment by bboreham** [comment]
It [seems](http://netdev.vger.kernel.narkive.com/icxCOlAC/netlink-recvmsg-and-msg-trunc) that "read next packet" isn't something you can expect to work.

A possible model is: https://github.com/imp/dnsmasq/blob/master/src/netlink.c#L102-L115
but using `MSG_PEEK` requires two syscalls to get the data, even if no truncation happens.

Another alternative is to close the netlink socket if the result is truncated and re-send the request with a larger receive buffer.

Still feels like we could special-case the 70% of calls which don't look at the return value, so they don't care if it is truncated.

**Comment by jellonek** [comment]
Post in first url seems to be a bit outdated as iproute2 uses MSG_PEEK to check the size of buffer to allocate in similar way how it's done in dnsmasq.

Closing/reopening netlink socket with resend of pkg/receive with larger buffer seems to be an interesting option.

**Comment by bboreham** [comment]
Fixed by #414, thanks!
