### ISSUE TITLE
Go Modules Support

### ISSUE THREAD

**Issue by prologic** [vishvananda/netlink#419]
Please add support for Go Modules (`go mod`) and tag/release a new version.

Right now I get build errors like:

```
...
undefined: netlink.FAMILY_V4
...
```

I suspect this is because the only tagged/released version is out-of-date and old compared with master.

Thanks!

**Comment by prologic** [comment]
My apologies; the build errors I'm seeing have nothing to do with a lack of GoModules support. They are in fact failing because I'm building on macOS :/

**Comment by DamonBlais** [comment]
@prologic Please close the issue if it's no longer relevant :)

Thank you.

**Comment by camilamacedo86** [comment]
How it was solved?
