### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by falzm** [vishvananda/netlink#424]
Hi

Could you please tag a new release for your package?  The [v1.0.0](https://github.com/vishvananda/netlink/releases/tag/v1.0.0) is more than 6 months old, using Go modules automatically pulls the latest tagged version of the module (there's a[ workaround for that](https://stackoverflow.com/questions/53682247/how-to-point-go-module-dependency-in-go-mod-to-a-latest-commit-in-a-repo), but it's not convenient) – and quite a lot of code is missing, compared to the [online documentation](https://godoc.org/github.com/vishvananda/netlink) which is based on master.

Thank you in advance!

**Comment by aboch** [comment]
:+1:

**Comment by onlyjob** [comment]
Due to lack of fresh release various projects already had to deviate from vendoring by tag...
Please, pretty please consider tagging a release for the sake of best practice.
Thanks.

**Comment by vishvananda** [comment]
@aboch seems like we should go ahead and do a 1.1.0 release?

**Comment by onlyjob** [comment]
Yes please. :)

**Comment by guesslin** [comment]
@vincentbernat hi, is there any news about the new release tag? I'd like to import this codes, but with [v1.0.0](https://github.com/vishvananda/netlink/tree/v1.0.0) is mid of 2018, and it's end of 2019 (there're almost 100 commits not included in the fresh tag)

https://github.com/vishvananda/netlink/issues/424#issuecomment-529412137
This is also a problem for those who using [go mod](https://blog.golang.org/using-go-modules).

Please consider tagging a new release.
Thanks

**Comment by gustavo-iniguez-goya** [comment]
Hi all!

@vishvananda do you think you could tag a new release? I'd like to use the new feature recently added https://github.com/vishvananda/netlink/commit/e499154279880a4823f0a01afb4d00de9f9690fb (SocketDiagTCPInfo). As far as I can tell works fine.

It's almost 1 year since last release.

**Comment by fach** [comment]
@aboch Would you folks mind tagging a new release? I'd like to use the work added in https://github.com/vishvananda/netlink/pull/585 without having to use a commit hash.

**Comment by AkihiroSuda** [comment]
@vishvananda Could you consider creating a new release? 🙏 The latest release v1.1.0 is more than 2 years old.

Just creating a beta tag like `v1.2.0-beta.0` might suffice for most people.

**Comment by vishvananda** [comment]
I've tagged a beta release. Please try it out and let me know if there are any issues and i'll upgrade it to an official 1.2.0

**Comment by dfateyev** [comment]
Probably, it's worth to tag a new beta / RC?

**Comment by aboch** [comment]
https://github.com/vishvananda/netlink/releases/tag/v1.2.1
