### ISSUE TITLE
create 802.1ad VLAN

### ISSUE THREAD

**Issue by knoll01** [vishvananda/netlink#429]
Is it possible to create an 802.1ad VLAN tag? Sort of like...

ip link add link eth0 name eth0.10 type vlan proto 802.1ad id 10

**Comment by DamonBlais** [comment]
@knoll01 Was this fixed for you when #437 was merged?

**Comment by knoll01** [comment]
> @knoll01 Was this fixed for you when #437 was merged?

I have not tested it. I worked around it, so it'll be a while before I can test it. Let's assume that it is fixed.
