### ISSUE TITLE
AddRule invalid argument

### ISSUE THREAD

**Issue by f1-outsourcing** [vishvananda/netlink#453]
I am trying to add this rule
ip rule add from 192.168.122.12/32 table 1

                        //rule for custom routing table
                        nsrule := &netlink.Rule{}
                        nsrule.Src = &net.IPNet{
                                        IP: result.IPs[0].Address.IP.To4(),
                                        Mask: net.CIDRMask(32, 32),
                                        }
                        nsrule.Table = 1

                        err = netlink.RuleAdd(nsrule)
                        if err != nil {
                                 return fmt.Errorf("Failed to add rule %q: %v %v",args.IfName,nsrule,err)
                        }

Failed to add rule "eth1": ip rule 0: from 192.168.122.12/32 table 1 invalid argument

Any idea's what I am doing wrong?

**Comment by vishvananda** [comment]
I suspect you are missing some required data. The iproute2 sets some default values for scope and type if they are not specified which we do not set. You might try including:
```
Scope:     unix.RT_SCOPE_UNIVERSE,
Type:      unix.RTN_UNICAST,
```

**Comment by f1-outsourcing** [comment]
Yes I already tried newRule but getting these
`gopath/src/github.com/containernetworking/plugins/plugins/main/macvtap/macvtap.go:288:14: cannot refer to unexported name netlink.newRule`
Is there a specific branch/version I need to checkout?

**Comment by vishvananda** [comment]
NewRule is (and should be) capitalized.

**Comment by f1-outsourcing** [comment]
Pfffff. yes indeed. Already got it working! Thanks for the great work here!

**Comment by vishvananda** [comment]
Good deal. Glad it was something simple.
