### ISSUE TITLE
Does not compile on Fedora 30

### ISSUE THREAD

**Issue by lzap** [vishvananda/netlink#455]
Hey,

the library does not compile on relatively modern Fedora 30. Looks like some new feature added recently.

    undefined: unix.IFF_MULTI_QUEUE

https://github.com/vishvananda/netlink/pull/330

**Comment by lzap** [comment]
Oh had an outdated golang.org/x/sys/unix package! Sorry for the noise.

**Comment by aboch** [comment]
Thank you for checking.
