### ISSUE TITLE
Broadcast address added to device while not explicitly requested

### ISSUE THREAD

**Issue by jerryz920** [vishvananda/netlink#471]
When I call AddrAdd(link, addr), the library currently automatically adds a broadcast address:
https://github.com/vishvananda/netlink/blob/master/addr_linux.go#L110

This can become problematic when we are using a /31 for p2p links. For example in our use case we have a GRE tunnel. If we want to assign e.g. 10.128.0.2/31 to one side, and then try to use 10.128.0.3 as gateway to route to remote tunnel, then it will report invalid gateway.

Can we have an option to not by default add brd address?

**Comment by jellonek** [comment]
In fact we are not consistent there with https://github.com/shemminger/iproute2/blob/master/ip/ipaddress.c#L2306 .

**Comment by DamonBlais** [comment]
@jerryz920 Was this fixed for you by incorporating #496 (specifically aad0bae) ?

**Comment by jerryz920** [comment]
@DamonBlais I think so. Thanks for the work!
