### ISSUE TITLE
netlink.LinkList() fails with "Wrong sender portid"

### ISSUE THREAD

**Issue by 2rigor** [vishvananda/netlink#497]
I lock goroutine to OS thread, iterate over containers switching to each container's network namespace using netns.Set() and call netlink.LinkList(). I get _Wrong sender portid 1885302884, expected 0_. I don't always get this error. But when I get, usually I get it for every second container.

Any ideas?
I am using the latest version of master (last commit on Sep-30 2019).
Thanks in advance.

**Comment by chkp-rigor** [comment]
The issue doesn't happen after upgrading to the latest "version", so the issue can be closed

**Comment by 2rigor** [comment]
the issue didn't reproduce since upgrading to the latest "version" 2 months ago, thus closing it
