### ISSUE TITLE
GTPPDPList() retrieves only one PDP

### ISSUE THREAD

**Issue by wmnsk** [vishvananda/netlink#505]
`GTPPDPList()` function in gtp_linux.go always returns only the last added `*PDP` object while multiple `*PDP`s are added. It seems the Kernel responds with all the entries but the function parses only the last one according to pcap.

As per my debugging, `msgs` returned at [L88](https://github.com/vishvananda/netlink/blob/master/gtp_linux.go#L88) has only one.

```shell-session
[[30 0 0 0 8 0 2 0 1 0 0 0 8 0 4 0 1 1 1 1 8 0 5 0 4 4 4 4 8 0 8 0 3 0 0 0 8 0 9 0 0 0 0 0]]
```

## Reproduction

Here's a snippet to reproduce this issue.

https://gist.github.com/wmnsk/cddce54f8574a1bf5a2b517aad5b63f4

## Output

Here are the logs from strace command and pcap using nlmon.

```shell-session
$ strace -s 100 -f -o strace.log -x ./gtp-tunnels
2020/01/06 10:54:40 Number of PDP by GTPPDPList(): 1
2020/01/06 10:54:40 PDP retrieved by GTPPDPList() (last added one): {Version: 1 TEI: 3/0 MS-Address: 4.4.4.4 Peer-Address: 1.1.1.1}
2020/01/06 10:54:40 PDP retrieved with GTPPDPByITEI() (ITEI=1): {Version: 1 TEI: 1/0 MS-Address: 2.2.2.2 Peer-Address: 1.1.1.1}
2020/01/06 10:54:40 PDP retrieved with GTPPDPByITEI() (ITEI=2): {Version: 1 TEI: 2/0 MS-Address: 3.3.3.3 Peer-Address: 1.1.1.1}
2020/01/06 10:54:40 PDP retrieved with GTPPDPByITEI() (ITEI=3): {Version: 1 TEI: 3/0 MS-Address: 4.4.4.4 Peer-Address: 1.1.1.1}
```

[strace.log](https://github.com/vishvananda/netlink/files/4024403/strace.log)

[gtp-nlmon.pcapng.gz](https://github.com/vishvananda/netlink/files/4024405/gtp-nlmon.pcapng.gz)

**Comment by wmnsk** [comment]
It seems the issue is happening at the following lines(hits `break` in first iteration), but I have not been able to find the best way to resolve it, as these lines are required and working right for other usage.

https://github.com/vishvananda/netlink/blob/ed8931371a8063912d9cf485a35447e791ee6f83/nl/nl_linux.go#L457-L459

**Comment by vishvananda** [comment]
So listing returns multiple messages without the multi flag being set? I don't think I've seen any other case where that happens.

**Comment by wmnsk** [comment]
> So listing returns multiple messages without the multi flag being set?

It seems so. I’d be happy to write a custom parser but I’m not sure if it’s a bug in Linux itself. FYI, with `libgtpnl` library, listing function works as expected.

https://github.com/osmocom/libgtpnl/blob/master/src/gtp-genl.c#L192

**Comment by wmnsk** [comment]
I've sent a patch that adds `NLM_F_MULTI` flag in the response of `gtp_genl_dump_pdp()` to kernel module maintainers. If they accept the patch, this issue can be closed without making any changes in your package(I think checking kernel version and prints warning can be a kind solution, though). I'll come back here when I heard of the updates from the maintainers.

http://lists.osmocom.org/pipermail/osmocom-net-gprs/2020-February/001126.html

FYI, I've confirmed that `GTPPDPList()` works well with the patch above using this code. 

https://gist.github.com/wmnsk/cddce54f8574a1bf5a2b517aad5b63f4#file-gtplist-2-go

```shell-session
$ sudo ./gtp-tunnels
2020/02/24 18:29:01 Number of PDP by GTPPDPList(): 3
2020/02/24 18:29:01 PDP retrieved by GTPPDPList() (0): {Version: 1 TEI: 3/0 MS-Address: 4.4.4.4 Peer-Address: 1.1.1.1}
2020/02/24 18:29:01 PDP retrieved by GTPPDPList() (1): {Version: 1 TEI: 1/0 MS-Address: 2.2.2.2 Peer-Address: 1.1.1.1}
2020/02/24 18:29:01 PDP retrieved by GTPPDPList() (2): {Version: 1 TEI: 2/0 MS-Address: 3.3.3.3 Peer-Address: 1.1.1.1}
2020/02/24 18:29:01 PDP retrieved with GTPPDPByITEI() (ITEI=1): {Version: 1 TEI: 1/0 MS-Address: 2.2.2.2 Peer-Address: 1.1.1.1}
2020/02/24 18:29:01 PDP retrieved with GTPPDPByITEI() (ITEI=2): {Version: 1 TEI: 2/0 MS-Address: 3.3.3.3 Peer-Address: 1.1.1.1}
2020/02/24 18:29:01 PDP retrieved with GTPPDPByITEI() (ITEI=3): {Version: 1 TEI: 3/0 MS-Address: 4.4.4.4 Peer-Address: 1.1.1.1}
```

**Comment by wmnsk** [comment]
Now the fix is accepted and merged to mainline. Please guide those who asks the same issue to use the latest kernel.

https://patchwork.ozlabs.org/project/netdev/patch/20200430050136.1837-1-ahochauwaaaaa@gmail.com/
