### ISSUE TITLE
netlink.LinkSetNsFd() returns a invalid argument issue

### ISSUE THREAD

**Issue by chenliu1993** [vishvananda/netlink#506]
Hi, I am using netlink to create veth pair. But when I call netlink.LinkSetNsFd() to set the veth into another netns in /proc/.../ns/net, a error called invalid argument happens.
I check the nsfd pass to LinkSetNsFd, it is 18, and I can do the same operation using "ip" command.
The system I use is Centos 7.

**Comment by chenliu1993** [comment]
the fd is closed before I call it. Close this

**Comment by tomasagata** [comment]
How did you solve it @chenliu1993?

**Comment by chenliu1993** [comment]
Hi @tomasagata , sorry I can't remeber exactly but based on my comments I think maybe I called ithis function after I closed the fd somethere I didn't notice.
