### ISSUE TITLE
netlink_linux.go missing declared constant from nl package. 

### ISSUE THREAD

**Issue by DandyDeveloper** [vishvananda/netlink#510]
Looks as though the constant for these family type definitions are missing in `netlink/nl`:

https://github.com/vishvananda/netlink/blob/ec20eb4fc390e0eee48c461f2a7005931615bc20/netlink_linux.go#L7

**Comment by vishvananda** [comment]
I'm not sure what you mean it is right here:

https://github.com/vishvananda/netlink/blob/master/nl/nl_linux.go#L21

**Comment by DandyDeveloper** [comment]
@vishvananda I'm sorry, ignore me. I made a grave mistake.
