### ISSUE TITLE
Geneve Remote is always 0.0.0.0

### ISSUE THREAD

**Issue by ahmetozer** [vishvananda/netlink#599]
Hi there,
I am trying to add geneve interface with unicast remote.
```go
geneveInterface := &netlink.Geneve{
		LinkAttrs: la,
		ID:        0x1000,
		Remote:    net.IPv4(123, 132, 112, 123)}
```
I watch my container and system is trying to send packets to 0.0.0.0 on dev lo0 not specified remote.
For debugging I add print in link_link.go
https://github.com/vishvananda/netlink/blob/fbe60771a0627ac5c8726a54c8cc3c5b81ccde01/link_linux.go#L2472

```go
if ip := geneve.Remote; ip != nil {
                if ip4 := ip.To4(); ip4 != nil {
                        test := data.AddRtAttr(nl.IFLA_GENEVE_REMOTE, ip )
                        fmt.Printf("remote addr  %v %v \n", test ,ip)
                } else {
                        data.AddRtAttr(nl.IFLA_GENEVE_REMOTE6, []byte(ip))
                }
        }
```
Here is output.
```bash
remote addr  &{{0 2} [0 0 0 0 0 0 0 0 0 0 255 255 123 132 112 123] []} 123.132.112.123
```

Kind Regards
Ahmet

**Comment by aboch** [comment]
Thanks @ahmetozer
Looks like you already identified the bug: Pass he IPv4 as 4 byte array whenyo uadd the attribute:
```
data.AddRtAttr(nl.IFLA_GENEVE_REMOTE, ip.To4())
```

Feel free to open a PR for it.
