### ISSUE TITLE
default state for network links

### ISSUE THREAD

**Issue by AdoHe** [vishvananda/netlink#60]
FYI. I use netlink to create bridge, veth pair. I found the initial state is `up`, so I don't need to call `LinkSetUp` function, is this right?

**Comment by vishvananda** [comment]
Generally I have to LinkSetUp new links. I'm not sure why they are defaulting to up for you.

**Comment by AdoHe** [comment]
@vishvananda Ok, thanks very much. Perhaps it is related with my OS.
