### ISSUE TITLE
ipset create failed. panic: invalid family

### ISSUE THREAD

**Issue by JiHanHuang** [vishvananda/netlink#609]
I want to use the latest features ipset in master branch.
I try to create new ipset list using './main create hash_test hash:ip', but I got:
```shell
# ./main create hash_test hash:ip
panic: invalid family

goroutine 1 [running]:
main.check(...)
	/root/opensource/netlink-master/cmd/ipset-test/main.go:146
main.cmdCreate(0xc00009e020, 0x2, 0x2)
	/root/opensource/netlink-master/cmd/ipset-test/main.go:105 +0x134
main.main()
	/root/opensource/netlink-master/cmd/ipset-test/main.go:73 +0x18f
```
System: centos 74  
Ipset: v6.29, protocol version: 6

**Comment by aboch** [comment]
Nothing in your description points to an issue in this library.
Unless you show your code, how you call this package methods, we cannot help.

**Comment by JiHanHuang** [comment]
> Nothing in your description points to an issue in this library.
> Unless you show your code, how you call this package methods, we cannot help.

I just build the 'netlink/cmd/ipset-test/main.go' and run it.

**Comment by aboch** [comment]
@corny PTAL
