### ISSUE TITLE
Syntax error in route_linux.go

### ISSUE THREAD

**Issue by KaushikKR-11** [vishvananda/netlink#630]
# github.com/vishvananda/netlink
../../vishvananda/netlink/route_linux.go:553:1: syntax error: non-declaration statement outside function body

this error is caused by the line 553 due to extra equals

553:      =======
554:     // RouteAddEcmp will add a route to the system.
555:    func RouteAddEcmp(route *Route) error {

Due to this non-declaration statement outside function body syntax error caused.

will be needful if sort out this error as early as possible.

**Comment by aboch** [comment]
Thanks @KaushikKR-11  can you pls push a fix?

**Comment by bjosv** [comment]
Can be closed due to #631
