### ISSUE TITLE
FilterAdd on loaded bpf program

### ISSUE THREAD

**Issue by fassisrosa** [vishvananda/netlink#658]
Hey there,

I have a loaded bpf program, it shows in 'bpftool prog'.

I would like to call netlink.FilterAdd to 'tc filter add' this program.
I have tried using netlink.BpfFilter.Id and tried using netlink.BpfFilter.Fd.
I am getting id and fd from program from bpf2go generated code that loads BPF prog.
In case of Id I verified that id matches Id of loaded prog. I am however always getting error (whether I use Id or Fd):

'no such file or directory'

The equivalent command I would like to run if using 'tc' would be:

tc filter add dev <myDevice> ingress bpf direct-action obj <objFile>

Is there any way I could load this already loaded prog as a filter?

Thanks,

Francisco.

**Comment by fassisrosa** [comment]
I think I have it, wrong version of .o file. Seems to be working now.

**Comment by mathiasxx** [comment]
I would like to see how you got that working.
