### ISSUE TITLE
[feature] uniform Handle.Close()

### ISSUE THREAD

**Issue by TheDiveO** [vishvananda/netlink#682]
First, thank you very much for providing the netlink module, I highly appreciate all the work put into it!

This is a small (_nitpit_?) feature request for aligning the Handle API more with what might be a typical resource release pattern. File resources, Docker clients, ... typically provide a `Close()` method to release their associated resources. In contrast, netlink defines `Handle.Delete()`. What about a graceful multi-step transition to `Handle.Close()`?

1. add `Handle.Close()` and map `Handle.Delete()` use it instead, so the API is kept, but aligned more with the typical(?) `Close()` pattern.
2. depreciate `Handle.Delete()`
3. _turn thumbs_
4. remove `Handle.Delete()`

**Comment by aboch** [comment]
>add Handle.Close() and map Handle.Delete() use it instead, so the API is kept

:+1:

**Comment by TheDiveO** [comment]
ping?
