### ISSUE TITLE
LinkSetMaster does not fail if bridge does not exist

### ISSUE THREAD

**Issue by gucki** [vishvananda/netlink#75]
I'm calling `LinkSetMaster` with a bridge that does not exist on the system like this `err = netlink.LinkSetMaster(link, &netlink.Bridge{LinkAttrs: netlink.LinkAttrs{Name: bridgeName}})`. The call returns success (nil), but it should return an error .

Using ip on the command line returns an error as expected:

    ip link set haa master aa
    Error: argument "aa" is wrong: Device does not exist

**Comment by krhubert** [comment]
https://github.com/vishvananda/netlink/pull/76
