### ISSUE TITLE
LinkByName crashing on v1.2.0-beta but works in master

### ISSUE THREAD

**Issue by DavidVentura** [vishvananda/netlink#755]
Hi
Commit 5e915e0149386ce3d02379ff93f4c0a5601779d5 fixes a crash I was having on ARMv7 when calling `LinkByName` -- `SetExtAck` would crash with `protocol not available`

While this was probably a bug, should `EnableErrorMessageReporting` get documented more ?
Even if this is closed immediately (there's no bug in HEAD after all), this might help others with the same issues.

**Comment by vishvananda** [comment]
I'll make a new beta tag that includes the fix from here:https://github.com/vishvananda/netlink/pull/752

**Comment by vishvananda** [comment]
New release posted: https://github.com/vishvananda/netlink/releases/tag/v1.2.1-beta.2

**Comment by dreamcat4** [comment]
could be related to this bug? https://github.com/moby/libnetwork/issues/2614
