### ISSUE TITLE
CentOS 7 netlink.addr broken with 1.2-beta

### ISSUE THREAD

**Issue by discostur** [vishvananda/netlink#774]
Hi,

flannel uses your library to select default interface / ip adresses: 

https://github.com/flannel-io/flannel/blob/d11ce9cf85c5fcb0dfb8d635f0b2a4125347ea68/main.go#L270

Since the netlink update to 1.2-beta support for CentOS 7 is broken and the default interface cannot be found. With CentOS 8 it is working. CentOS 7 works with older netlink versions before 1.2-beta ... 

Can you try to fix c7 support?

Flannel issue: https://github.com/flannel-io/flannel/issues/1574

Thanks,
Regards
Kilian

**Comment by vishvananda** [comment]
Thanks for the report. Following the call stack it looks like the eventual call is to AddrList:
https://github.com/flannel-io/flannel/blob/d11ce9cf85c5fcb0dfb8d635f0b2a4125347ea68/pkg/ip/iface.go#L30
I'll look for any obvious changes in that code. It looks like AddrList is returning an empty list? I might have to try to find a centos 7 box to do a git bisect

**Comment by vishvananda** [comment]
This looks like the same error here: https://github.com/vishvananda/netlink/issues/755

**Comment by vishvananda** [comment]
I'll make a new beta tag that includes the fix from here:https://github.com/vishvananda/netlink/pull/752

**Comment by discostur** [comment]
@vishvananda thanks for your fast response - i can confirm this works now for centos 7 ;)
