### ISSUE TITLE
Is RouteList incorrectly setting RT_FILTER_OIF

### ISSUE THREAD

**Issue by rickpayne** [vishvananda/netlink#817]
First time go user, so this could be me - but I was trying to get a list of the routes on my box. Should be simple?
```
package main

import (
    "fmt"
    "github.com/vishvananda/netlink"
)

func main() {
    routes,err := netlink.RouteList(nil, netlink.FAMILY_V4)
    if err != nil {
            fmt.Printf("could not list: %v\n", err)
    }
    for k, v := range routes {
        fmt.Printf("%d: %v\n", k, v)
    }
}
```
I get nothing back. Some debugging shows that the parsed routes are discarded because the OIF is 2, rather than 0 (because my box has a few interfaces and the output interface is not the first one I guess). I think the issue is because we end up here:
```
func (h *Handle) RouteList(link Link, family int) ([]Route, error) {
	routeFilter := &Route{}
	if link != nil {
		routeFilter.LinkIndex = link.Attrs().Index
	}
	return h.RouteListFiltered(family, routeFilter, RT_FILTER_OIF)
}
```
So even if link is nil, an RT_FILTER_OIF is set. I'd have expected a call to RouteList with a nil filter should do just that? What have I missed?

**Comment by cjmakes** [comment]
This used to be the default behavior and was broken in #782 and will be fixed in #825
