### ISSUE TITLE
Can RouteListFiltered working in the kernel?

### ISSUE THREAD

**Issue by wofanli** [vishvananda/netlink#843]
Looks like RouteListFiltered is working in the user space, not in the kernel space. Am I right? 
Can we do the filtering in Kernel, which causes less overhead?

After going through the related C code of iproute2, it seems the Linux kernel supports filter rules when dumping the route tables.

**Comment by frozenprocess** [comment]
I think it depends on how you use it. 
You should be able to use the strict flag to offload the filtering to Kernel.

For example, without the strict check flag, kernel spits out all the routes and you have to deal with it in the userspace, with the strict flag, kernel will give you what you actually asked ( or an error :D ) .

```go
netlink.NewHandle(syscall.NETLINK_ROUTE)
hn.SetStrictCheck(*strictCheck)
hn.RouteListFiltered(stuff that should happen here)
```

**Comment by wofanli** [comment]
@frozenprocess Thanks for you hint. I'll try it.

**Comment by orientlu** [comment]
how can i filter RTM_F_CLONED route in kernel , it too much
