### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by martinkennelly** [vishvananda/netlink#875]
Hey!
Any interest in a new release? Its been awhile.
No pressure.

**Comment by aboch** [comment]
Let's do it after a round of merging.

**Comment by martinkennelly** [comment]
Thank you @aboch !! Keep this open to track it.

**Comment by mlguerrero12** [comment]
@aboch, would it possible to have a new release please?

**Comment by martinkennelly** [comment]
Closing as dupe of other issues. Theres no real release schedule anyway.
