### ISSUE TITLE
LinkByName with an altname that exceeds the 15 char limit fails

### ISSUE THREAD

**Issue by steiler** [vishvananda/netlink#955]
The test for altnames only contains short (<15 char) altnames.
altnames are allowed to carry more characters. See:

```bash
# Query via Name
mava@server01:~/projects$ ip l show dev foobar
22: foobar: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 72:42:33:ae:b7:bf brd ff:ff:ff:ff:ff:ff
    altname some_longer_altname

# Query via long AltName
mava@server01:~/projects$ ip l show dev vx-some_very_long_node_name_l1_e1-1
22: foobar: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 72:42:33:ae:b7:bf brd ff:ff:ff:ff:ff:ff
    altname some_longer_altname
```
However, using this library I am getting the following error:

```bash
mava@server01:~/projects/netlink$ sudo go test -timeout 30s -run ^TestLinkAltName$ github.com/vishvananda/netlink
--- FAIL: TestLinkAltName (0.00s)
    link_test.go:1937: numerical result out of range: Attribute failed policy validation
FAIL
FAIL    github.com/vishvananda/netlink  0.005s
FAIL
```
Find the adjusted test here:
https://github.com/steiler/netlink/commit/32fec641ca0b95078a2e620ba6b17023c0efac02

@SchSeba Maybe you can take a look at this. After implementing #862

**Comment by steiler** [comment]
@SchSeba I have come up with a fix that does work. But I'm not sure if it is the right way to tackle this.
See #956

**Comment by hellt** [comment]
Thanks for the PR @steiler and your review @aboch 

@aboch @vishvananda is there a planned date to have the next tagged release?
