### ISSUE TITLE
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb2524d]

### ISSUE THREAD

**Issue by huangchengwu** [vishvananda/netlink#987]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb2524d]

goroutine 1972 [running]:
github.com/vishvananda/netlink.parseActions({0xc0062fa000, 0x4, 0x2?})
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:981 +0x50d
github.com/vishvananda/netlink.(*Flower).decode(0xc001387680, {0xc0062f2488, 0x15, 0x411e7b?})
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:223 +0x1cb
github.com/vishvananda/netlink.parseFlowerData(...)
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:1119
github.com/vishvananda/netlink.(*Handle).FilterList(0x690a3b0, {0x446c3b8, 0xc003fafc80}, 0xfffffff2)
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:512 +0x854
github.com/vishvananda/netlink.FilterList({0x446c3b8, 0xc003fafc80}, 0xfffffff2)
	/go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/filter_linux.go:423 +0xfd
github.com/cilium/cilium/pkg/datapath/loader.removeObsoleteNetdevPrograms({0xc001c78f00, 0x4, 0x3e0a025?})
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:275 +0x427
github.com/cilium/cilium/pkg/datapath/loader.(*loader).reloadHostDatapath(0xc00100a360, {0x44c34b0, 0xc004ad03c0}, 0xc004481950, {0xc001c78f00, 0x4, 0x4})
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:429 +0x12b3
github.com/cilium/cilium/pkg/datapath/loader.(*loader).reloadDatapath(0xc00100a360, {0x44c34b0, 0xc004ad03c0}, 0xc004481950)
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:472 +0xec5
github.com/cilium/cilium/pkg/datapath/loader.(*loader).ReloadDatapath(0xc00100a360, {0x448f298, 0xc004c82540}, {0x44c34b0, 0xc004ad03c0}, 0xc004cbe230)
	/go/src/github.com/cilium/cilium/pkg/datapath/loader/loader.go:595 +0x207
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).realizeBPFState(0xc001bce408, 0xc004cbe008)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:664 +0x3b8
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerateBPF(0xc001bce408, 0xc004cbe008)
	/go/src/github.com/cilium/cilium/pkg/endpoint/bpf.go:586 +0x49f
github.com/cilium/cilium/pkg/endpoint.(*Endpoint).regenerate(0xc001bce408, 0xc004cbe008)
	/go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:458 +0x9bd
github.com/cilium/cilium/pkg/endpoint.(*EndpointRegenerationEvent).Handle(0xc001b82280, 0xc002968cc0)
	/go/src/github.com/cilium/cilium/pkg/endpoint/events.go:57 +0x1df
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run.func1()
	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:244 +0x133
sync.(*Once).doSlow(0xc0014299e0?, 0x0?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).run(0xc0020f2d80?)
	/go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:232 +0x3c
created by github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run in goroutine 1

**Comment by Matus-p** [comment]
there is missing "if action != nil" here: https://github.com/vishvananda/netlink/blob/main/filter_linux.go#L923
this can happen for example when actionType == "vlan"
